### ISSUE TITLE
Баг в рисовании 

### ISSUE THREAD

**Issue by wizardOfOz21** [bmstu-iu9/ptp2022-7-svg-editor#17]
Случайно заметил, что нельзя начать рисование в области, в которой уже расположен другой объект (особенно заметно в заполненной цветом области), не имеет даже значения, на каком слое этот объект находится. Причем продолжить рисование, начатое в свободной области, над любым объектом можно.

**Comment by Mazdaywik** [comment]
Хоть бы ссылку на коммит, исправляющий ошибку дали.

**Comment by AngelicHedgehog** [comment]
> Хоть бы ссылку на коммит, исправляющий ошибку дали.

**Comment by Mazdaywik** [comment]
А ещё лучше в сам коммит добавлять ссылку на баг:
```bash
git commit -m "Исправление бага с рисованием объектов на других (#17)"
```

**Comment by AngelicHedgehog** [comment]
> А ещё лучше в сам коммит добавлять ссылку на баг:
> 
> ```shell
> git commit -m "Исправление бага с рисованием объектов на других (#17)"
> ```

Понял, учту
