### ISSUE TITLE
Баг с загрузкой файла

### ISSUE THREAD

**Issue by Kabane-UN** [bmstu-iu9/ptp2022-7-svg-editor#23]
По время соединения веток нашли баг, с тем что не работает сохранение svg, и я заметил,
что ты зачем-то в design.js создал свой скрипт сохранения svg (причем не работающий),
можешь объяснить пж причину или исправить?

**Comment by GarryNeKasparov** [comment]
Он остался там после раннего соединения с develop веткой, немедленно удаляю
