### ISSUE TITLE
Дубликаты signup & login

### ISSUE THREAD

**Issue by Kabane-UN** [bmstu-iu9/ptp2022-7-svg-editor#24]
Привет, можешь объяснить, зачем ты в templates/svg_editor создал login.html и signup.html

**Comment by vyydra** [comment]
Андрей, ты перепутал: это я их добавила. Они не нужны – моя ошибка. Надо их удалить из ветки develop со следующим pull request, который я, например, создам. Кстати, для этих двух страниц стили прописаны еще в svg_editor/css/main.css. Это не критично, но тоже, понятное дело, нужно убрать. 
Допустим, я буду держать это в голове и добавлю сюда пул реквест, который решит проблему, если кто-то не сделает этого раньше
