### ISSUE TITLE
Отображение холста при нестандартых условиях

### ISSUE THREAD

**Issue by AngelicHedgehog** [bmstu-iu9/ptp2022-7-svg-editor#29]
Последний добавленный мной инструмент - это курсор. Он позволяет изменять размер холста (через изменение параметров width и heidht главного svg блока и всех в него вложенных) и двигать его по странице (путём изменения таких параметров стиля главного блока svg, как margin-left и margin-top).

На данный момент при перемещении холста в область инструментов, параметров и верхней панели, он перекрывает их.
Так же при перемещении холста ближе к панели слоёв его поведение становится сильно отличным от ожидаемого.

![problem](https://user-images.githubusercontent.com/102258145/184006519-70a5bf5e-8fc1-4f8f-b540-fd76df7c66a2.gif)

p.s. напоминаю, что для того, чтобы прикрепить коммит к данной проблеме нужно в комментарии(названии) коммита указать номер проблемы (пример: `git commit -m "Решение проблемы холста #29"`)

**Comment by GarryNeKasparov** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/52318064/184528347-470fe869-5086-4eaf-8ff6-8c1658cb8480.gif)
Кажется, теперь работает как надо. Только проблема, как доставать область, если она вдруг полностью уйдет за экран (не критично! так как достается растягиванием)

**Comment by AngelicHedgehog** [comment]
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/52318064/184528347-470fe869-5086-4eaf-8ff6-8c1658cb8480.gif) [ ![ezgif com-gif-maker](https://user-images.githubusercontent.com/52318064/184528347-470fe869-5086-4eaf-8ff6-8c1658cb8480.gif) ](https://user-images.githubusercontent.com/52318064/184528347-470fe869-5086-4eaf-8ff6-8c1658cb8480.gif) [ ](https://user-images.githubusercontent.com/52318064/184528347-470fe869-5086-4eaf-8ff6-8c1658cb8480.gif) Кажется, теперь работает как надо. Только проблема, как доставать область, если она вдруг полностью уйдет за экран (не критично! так как достается растягиванием)

Теперь работает идеально! 🤩
По поводу того, что уходит за экран - это так критично, поэтому с лёгкой руки предлагаю забить.
