### ISSUE TITLE
README.md Описания инструментов

### ISSUE THREAD

**Issue by AngelicHedgehog** [bmstu-iu9/ptp2022-7-svg-editor#30]
# Требуется добавить документацию к каждому из имеющихся инструментов в [README.md#инструменты ![АХАХАХА](https://user-images.githubusercontent.com/102258145/184250235-e1273a41-d48a-4cd4-85c7-5c4ffaea9151.png)](../blob/final-readme/README.md#инструменты)

##### мне вот интересно, насколько окей делать вот такие таски, адресованные себе же?...

**Comment by Mazdaywik** [comment]
Нормально, нет никаких проблем. [Здесь](https://github.com/bmstu-iu9/refal-5-lambda/issues) таких много.

**Comment by AngelicHedgehog** [comment]
> Нормально, нет никаких проблем. [Здесь](https://github.com/bmstu-iu9/refal-5-lambda/issues) таких много.

Тогда ладно)
