### ISSUE TITLE
README.md Документация по инсталяции проекта

### ISSUE THREAD

**Issue by AngelicHedgehog** [bmstu-iu9/ptp2022-7-svg-editor#34]
# Требуется добавить документацию к установке всего необходимого для работы проекта и его запуска в [README.md#инсталяция-проекта ![](https://user-images.githubusercontent.com/102258145/184253379-ed9e56c4-853b-4be2-840b-fe141ca882de.png)](https://github.com/bmstu-iu9/ptp2022-7-svg-editor/blob/final-readme/README.md#инсталяция-проекта)

**Comment by Kabane-UN** [comment]
Закончил!
