### ISSUE TITLE
Добавление нового диалогового окна

### ISSUE THREAD

**Issue by AngelicHedgehog** [bmstu-iu9/ptp2022-7-svg-editor#36]
# Я вынес ввод содержимого для инструмента Текст в отдельную функцию 
```JavaScript
function getText(mesege: string, _default: string): string
```
## От тебя требуется перегрузить (или лучше переписать) эту функцию так, чтобы при её вызове открывалось диалоговое окно на подобии тех, что появляются после нажатия кнопок New, Save и других из панельки управления на главном экране.
Сейчас так | Нужно так
|:---:|:---:|
![old_code](https://user-images.githubusercontent.com/102258145/184504089-48e0dc2d-ac2a-4a12-a6a5-87082201ae6f.png) | ![new_code](https://user-images.githubusercontent.com/102258145/184504098-3ce1e429-b199-42b7-a755-1bd27b830355.png)
![old_face](https://user-images.githubusercontent.com/102258145/184504113-4ece67b3-5db1-4476-949d-aa32f5e2b771.png) | ![new_face](https://user-images.githubusercontent.com/102258145/184503668-87d49214-d301-426f-84dd-35d01786efb8.png)

p.s. советую писать функцию именно с такими двумя аргументами, ведь её тогда можно будет использовать так же для запроса названия нового слоя

**Comment by GarryNeKasparov** [comment]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/52318064/184532485-78f378f7-857e-403a-9c59-02fb15c8d458.gif)
Я правильно понял, что _default это текст, который нарисуется, если пользователь ничего не введёт?
**Пришлось добавить в textUp, вот эту строчку, т.к без неё любое нажатие на окно заново вызывает функцию рисования => окно ввода очищается и ввести ничего нельзя (это я к тому, вдруг какой баг вылезет)
![image](https://user-images.githubusercontent.com/52318064/184532516-d1a26989-0d15-4091-b7d8-a9c316f79ae3.png)

**Comment by AngelicHedgehog** [comment]
> Я правильно понял, что _default это текст, который нарисуется, если пользователь ничего не введёт? **Пришлось добавить в textUp, вот эту строчку, т.к без неё любое нажатие на окно заново вызывает функцию рисования => окно ввода очищается и ввести ничего нельзя (это я к тому, вдруг какой баг вылезет) ![image](https://user-images.githubusercontent.com/52318064/184532516-d1a26989-0d15-4091-b7d8-a9c316f79ae3.png)

Да, всё верно, спасибо!
