### ISSUE TITLE
Работа над иконками (и по мелочи)

### ISSUE THREAD

**Issue by AngelicHedgehog** [bmstu-iu9/ptp2022-7-svg-editor#37]
# Требуется:
* Исправить следующие иконки:

Название файла | Что не так
|:---:|:---:|
line.svg | ![line.svg](https://user-images.githubusercontent.com/102258145/184536352-028a266e-ec60-4ec8-b66d-85655459722f.png)
line-active.svg | ![line-active.svg](https://user-images.githubusercontent.com/102258145/184536705-7a7ecb9b-4a60-4361-8393-dc2e6e4061cc.png)
skew.svg | ![skew.svg](https://user-images.githubusercontent.com/102258145/184536414-281600c4-e409-47d5-bb58-94cef701f302.png)
compress.svg | ![comress.svg](https://user-images.githubusercontent.com/102258145/184536473-7b064c0e-bfa6-4ba1-a7ca-2013a80ea98e.png)
layer.svg | ![layer.svg](https://user-images.githubusercontent.com/102258145/184536661-cb8ceb5b-518c-4ef5-b75e-b031a89c475e.png)
* Поменять все вхождения подстроки "tenscompress" во всём коде на "compress" (мне подсказали, что лучше использовать грамматически правильные названия)
* Добавить инструмент перемещения (move)

**Comment by GarryNeKasparov** [comment]
Compress поменял, а с остальными что не так? Там специально закрашено в цвет фона (я не могу убрать заливку, ибо это значки из интернета)

**Comment by AngelicHedgehog** [comment]
> Compress поменял, а с остальными что не так? Там специально закрашено в цвет фона (я не могу убрать заливку, ибо это значки из интернета)

Окей, я сам попробую исправить.
Что по добавлению move?
