### ISSUE TITLE
Баг и рамкой

### ISSUE THREAD

**Issue by Kabane-UN** [bmstu-iu9/ptp2022-7-svg-editor#39]
![Снимок экрана от 2022-08-15 19-24-58](https://user-images.githubusercontent.com/60570949/184675406-7a8b9ff2-799e-4ee1-9882-8528a151b7c5.png)

Заметил баг, что синяя рамка фигуры остается при сохранении файла

**Comment by AngelicHedgehog** [comment]
## Для этого нужно перед сохранением файла вызвать функцию `breakDrawing()`.
### Поскольку все выделения являются частью главного блока svg, их нужно явно удалять перед сохранением файла, а отследить все события сохранения я не в состоянии.

**Comment by AngelicHedgehog** [comment]
> ![Снимок экрана от 2022-08-15 19-24-58](https://user-images.githubusercontent.com/60570949/184675406-7a8b9ff2-799e-4ee1-9882-8528a151b7c5.png)
> 
> Заметил баг, что синяя рамка фигуры остается при сохранении файла
> 
> 

Не забудь привязать коммит, когда сделаешь, что написано ниже
