### ISSUE TITLE
Стайлинг страницы редактора

### ISSUE THREAD

**Issue by Kabane-UN** [bmstu-iu9/ptp2022-7-svg-editor#41]
Для работы с несколькими файлами, я в низу страницы редактора создал панельку на которой отображаются названия файлов с подсветкой активного файла, возможность переключения и удаления. Дизайнеры пж доведите ее стиль до ума. В место ораньжевого кружочка вставьте крестик. Будьте аккуратны функционал удаления файла привязан в этому кружочку, а функционал переключения в идеале ко всей остальной области, поэтому они не должны пересекаться.
![Снимок экрана от 2022-08-15 19-38-27](https://user-images.githubusercontent.com/60570949/184834666-1f36ce7d-4cfe-414a-b517-7dfa3bf11349.png)

**Comment by GarryNeKasparov** [comment]
Забыл в коммите указать эту проблему, крестик поставил, скрипты не трогал, сами квадратики мне нравятся, как выглядят
![image](https://user-images.githubusercontent.com/52318064/185398846-5e5c7fba-f79b-4950-8cbd-2747a5a23067.png)
**Еще** я заметил, что если создать два файла с одинаковым названием, то между ними нельзя переключаться

**Comment by AngelicHedgehog** [comment]
> Забыл в коммите указать эту проблему, крестик поставил, скрипты не трогал...
В каком коммите? (добавить ссылку на коммит в комменте к задаче, если забыл указать номер задачи в комментарии к коммиту)


> **Еще** я заметил, что если создать два файла с одинаковым названием, то между ними нельзя переключаться
Вынеси, если не трудно, эту проблему в отдельную задачу, адресованную Андрею, с биркой "инвалид"(отличие фактического поведения от ожидаемого)

**Comment by Kabane-UN** [comment]
Я ожидал, что такое будет учитывая, что нет никакой проверки на коллизию

**Comment by Kabane-UN** [comment]
Создал issue и решил проблему с коллизией
