### ISSUE TITLE
Баг с увеличением и перетаскиванием холста

### ISSUE THREAD

**Issue by Kabane-UN** [bmstu-iu9/ptp2022-7-svg-editor#42]
С перетаскиванием страницы есть баг. Дело в том что сейчас можно перетащить холст  хоть даже на панель инструментов. Такой дичи быть не должно, нужно подумать над тем, как ограничить перетаскивание и расширение только рабочей областью.
![Снимок экрана от 2022-08-16 11-34-47](https://user-images.githubusercontent.com/60570949/184836161-50627d97-1b9e-4fca-9a26-d4767dd52864.png)

**Comment by Kabane-UN** [comment]
Также очевидно, нужно определиться с размером рабочей области

**Comment by AngelicHedgehog** [comment]
> С перетаскиванием страницы есть баг. Дело в том что сейчас можно перетащить холст  хоть даже на панель инструментов. Такой дичи быть не должно, нужно подумать над тем, как ограничить перетаскивание и расширение только рабочей областью.
> ![Снимок экрана от 2022-08-16 11-34-47](https://user-images.githubusercontent.com/60570949/184836161-50627d97-1b9e-4fca-9a26-d4767dd52864.png)
> 

Разве решение Влада(#29) не подходит?

**Comment by GarryNeKasparov** [comment]
> > С перетаскиванием страницы есть баг. Дело в том что сейчас можно перетащить холст  хоть даже на панель инструментов. Такой дичи быть не должно, нужно подумать над тем, как ограничить перетаскивание и расширение только рабочей областью.
> > ![Снимок экрана от 2022-08-16 11-34-47](https://user-images.githubusercontent.com/60570949/184836161-50627d97-1b9e-4fca-9a26-d4767dd52864.png)
> 
> Влад, вроде, уже решил этот вопрос(#29). Проблем с перетаскиванием за границы проблемы не вижу, можно просто у курсора добавить функционал возвращения левого верхнего угла на исходную позицию. Могу этим заняться, если критично, это по моей части.
![image](https://user-images.githubusercontent.com/52318064/185400196-9903d5bb-81f5-4c66-810d-2e279bdfaa79.png)
Тут баг немного другой, я пока не понял, с чем связано такое поведение (у Андрея хотя бы нет второго белого квадрата!)

**Comment by AngelicHedgehog** [comment]
В ходе обсуждения было принят то решение воспринимать подобное поведение не как баг, а как фичу
