### ISSUE TITLE
Нудно отстайлить письма

### ISSUE THREAD

**Issue by Kabane-UN** [bmstu-iu9/ptp2022-7-svg-editor#43]

**Comment by AngelicHedgehog** [comment]
## @SatybaldievT, для привязки коммита, закрывающего задачу, требуется в комментарии (названии) коммита указать номер закрываемой задачи, например, "change email #43".

### В случае, если забыл это сделать, перед закрытием задачи следует в комментариях к ней оставить ссылку на коммит, закрывающий задачу, например, https://github.com/bmstu-iu9/ptp2022-7-svg-editor/commit/ea612f77d569cb15adf971ea97f74cd570e668a1.

---

##### постарайся с уважением относиться к участником твоей команды, захотевшим посмотреть решение данной задачи

**Comment by Kabane-UN** [comment]
Ну типа задача закрыта [этим коммитом](https://github.com/bmstu-iu9/ptp2022-7-svg-editor/commit/ea612f77d569cb15adf971ea97f74cd570e668a1)
