### ISSUE TITLE
Что с этими ветками?

### ISSUE THREAD

**Issue by AngelicHedgehog** [bmstu-iu9/ptp2022-7-svg-editor#44]
# Требуется либо подтвердить галочкой важность ветки, либо удалить её
### Ветки, которые не обновлялись 8 и более дней:
 * [ ] [project-load (Гамид)](https://github.com/bmstu-iu9/ptp2022-7-svg-editor/tree/project-load)
 * [x] [account-gallery (Андрей)](https://github.com/bmstu-iu9/ptp2022-7-svg-editor/tree/account-gallery)
 * [x] [production (Андрей)](https://github.com/bmstu-iu9/ptp2022-7-svg-editor/tree/production)
 * [x] [account-interface (Варя)](https://github.com/bmstu-iu9/ptp2022-7-svg-editor/tree/account-interface)

**Comment by vyydra** [comment]
Удалила свою ветку, но создала другую с таким же именем (account-interface), в которой буду продолжать работу

**Comment by Kabane-UN** [comment]
Production нужна как не странно для production. Account gallery я не удаляю потому что в ней есть фронтэнд для работы с файлами, который из текущей версии дизайна просто выпилен, оставлю пока на всякий случай и удалю когда Влад сам доделает весь фронтэнд связанный с сохранением и ТД.

**Comment by AngelicHedgehog** [comment]
> Production нужна как не странно для production. Account gallery я не удаляю потому что в ней есть фронтэнд для работы с файлами, который из текущей версии дизайна просто выпилен, оставлю пока на всякий случай и удалю когда Влад сам доделает весь фронтэнд связанный с сохранением и ТД.

Так как это чисто твои ветки, можно было обойтись простой установкой галочек, ну ладно)

**Comment by wizardOfOz21** [comment]
Удалил ветку project-load
