### ISSUE TITLE
Нужно отредачить стили для ссылки на профиль

### ISSUE THREAD

**Issue by Kabane-UN** [bmstu-iu9/ptp2022-7-svg-editor#46]
Нужно отредачить стили для ссылки на профиль.
![Снимок экрана от 2022-08-19 18-31-24](https://user-images.githubusercontent.com/60570949/185654290-1830fc13-4de6-4030-96be-de170b8aefbd.png)
Работы не много просто отцентровать, увеличить текст, мб изменить шрифт и добавить анимацию при наведении

**Comment by AngelicHedgehog** [comment]
Задача решена этим коммитом: https://github.com/bmstu-iu9/ptp2022-7-svg-editor/commit/7ac9c17a7fb61c0ec2ba9f9c60c7a664fdac99ef
