### ISSUE TITLE
Отсутствует фонт для функциона работы с файлами в редакторе

### ISSUE THREAD

**Issue by Kabane-UN** [bmstu-iu9/ptp2022-7-svg-editor#47]
Чтобы ничего не пропустить сделал полный список функционала работы с файлами который был реализован уже давно,
но после соединения с **[@GarryNeKasparov](https://github.com/GarryNeKasparov)**  пропали интерфейсы
Если, что все старые интерфейсы есть в [этой ветке](https://github.com/bmstu-iu9/ptp2022-7-svg-editor/tree/account-gallery)
Пж помечайте, если что-то сделали (Ну и конечно помечайте комиты и добавляйте ссылки на пулреквесты)

Реализованы частично (нужно допилить стили и местами соединить с моим кодом):
 * [x] new создание нового файла
 * [x] save сохранение текущего файла
 * [x] download экспорт файла с сервера
 * [x] open импорт файла на сервер

Вообще не реализован:
 * [x] edit открытие файла с сервера
 * [x] save as сохранение как
 * [x] delete удаление выбранного файла с сервера
 * [x] delete all удаление всех файлов
 * [x] view просмотр файлов находящихся на сервере
 
P.S. 
edit, delete, delete all, download, view я считаю лучше объединить в одно окошко, так как они связаны с view

**Comment by AngelicHedgehog** [comment]
## Одна небольшая оговорочка по поводу данного задания: при выборе нового пункта для выполнения из списка выше расставляйте приоритеты(интуитивно), так как полагаю, сделать всё идеально работающим может не получиться.

# Берегите себя, свои силы и нервы!
