### ISSUE TITLE
Странное поведение истории вкупе с загрузкой файла

### ISSUE THREAD

**Issue by Kabane-UN** [bmstu-iu9/ptp2022-7-svg-editor#49]
Заметил такой баг при загрузке файла история работает странно, и ну вы сами видите
![Запись-экрана-от-21 08 2022-23_00_28](https://user-images.githubusercontent.com/60570949/185809022-f3f578f5-84f9-4dfb-a8da-c5bd16fae1cf.gif)

**Comment by AngelicHedgehog** [comment]
Этот вопрос так же, как и #39, я переадресую тебе, @Kabane-UN.
Здесь тебе нужно будет добавить вызов функции `historyNew()` после загрузки существующего файла и делов.
Исправить этот баг через свою часть кода я не могу, так как у меня нет возможности отличить загрузку файла от его создания.

**Comment by Kabane-UN** [comment]
При попытке сделать так historyNew() начинает выдавать ошибку и перестанет работать 
![Снимок экрана от 2022-09-04 14-28-07](https://user-images.githubusercontent.com/60570949/188311064-bdc42ac6-be3b-41e8-9fad-beabecdda8d8.png)
![Снимок экрана от 2022-09-04 14-28-54](https://user-images.githubusercontent.com/60570949/188311081-87f34dbc-ba8e-46d3-949a-d996e247fa00.png)

**Comment by AngelicHedgehog** [comment]
> При попытке сделать так historyNew() начинает выдавать ошибку и перестанет работать ![Снимок экрана от 2022-09-04 14-28-07](https://user-images.githubusercontent.com/60570949/188311064-bdc42ac6-be3b-41e8-9fad-beabecdda8d8.png) ![Снимок экрана от 2022-09-04 14-28-54](https://user-images.githubusercontent.com/60570949/188311081-87f34dbc-ba8e-46d3-949a-d996e247fa00.png)

Это происходит из-за того, что функция вызывается до определения draw (холста).
Нужно либо добавить в тело функции следующий код: `if (draw == null) return`, либо вызывать её после определения холста.

**Comment by Kabane-UN** [comment]
Ну это не решает проблему, есть ли способ сделать historyNew работоспособной до определения холста?

**Comment by Kabane-UN** [comment]
Да и к тому же, historyNew даже если не выдает ошибок и находится после объявления холста, все равно не помогает от странного поведения

**Comment by Kabane-UN** [comment]
я дофига времени убил,чтобы понять почему это чертова история сливает данные файла и первый рисунок в одну ячейку, в итоге нихрена не понял. В общем, если до завтра не будет найдено решение то данное issue замораживается на неопределенный срок

**Comment by Kabane-UN** [comment]
Потому что, после загрузки файла история пуста, а при первом же рисовании в нее магический образом одновременно добавляется и новый рисунок и весь загруженный рисунок.  Магия не иначе. Либо какой-то недочет в добавлении новой информации в историю

**Comment by AngelicHedgehog** [comment]
Понял, постараюсь решить проблему в draw.js

> Потому что, после загрузки файла история пуста, а при первом же рисовании в нее магический образом одновременно добавляется и новый рисунок и весь загруженный рисунок. Магия не иначе. Либо какой-то недочет в добавлении новой информации в историю
