### ISSUE TITLE
Ошибка с csrf-токеном

### ISSUE THREAD

**Issue by AngelicHedgehog** [bmstu-iu9/ptp2022-7-svg-editor#52]
## При попытке отправления пакетов на [сервер](http://185.105.224.63:8000/) возвращается ошибка:
```
Ошибка доступа (403)
Ошибка проверки CSRF. Запрос отклонён.
В отладочном режиме доступно больше информации. Включить отладочный режим можно, установив значение переменной DEBUG=True.
```

**Comment by Kabane-UN** [comment]
Данная ошибка возникала только на удаленном сервере, и была связана с конфигами nginx, ошибку исправил опять же на cервере
