### ISSUE TITLE
Не могу зайти

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/ptp2022-7-svg-editor#64]
Создал пользователя `mazdaywik` с паролем `Qaz12345`. Ввожу в окне логина — не заходит.

**Comment by AngelicHedgehog** [comment]
> Создал пользователя `mazdaywik` с паролем `Qaz12345`. Ввожу в окне логина — не заходит.

Это произошло из-за того, что аккаунт не был создан. Ошибка заключается в том, что для создания аккаунта требуется верификация пользователя, а адрес почты, с которой рассылаются письма-подтверждения, был заморожен из-за предположительного спама.

Письмо в поддержку mail.ru уже отправлено, но если Вы согласны, мы можем искусственно создать аккаунт с нужными полями для продолжения проверки.

**Comment by Mazdaywik** [comment]
Оценки уже поставил в ведомость, поэтому я просто подожду разблокировки ящика.

**Comment by Kabane-UN** [comment]
Добрый день, ящик разблокировали

**Comment by Kabane-UN** [comment]
> Оценки уже поставил в ведомость, поэтому я просто подожду разблокировки ящика.

Добрый день, ящик разблокировали

**Comment by Mazdaywik** [comment]
Точно разблокировали? Я попробовал создать аккаунт, на <a.v.konovalov87@mail.ru> мне ничего не пришло.

**Comment by Kabane-UN** [comment]
> Точно разблокировали? Я попробовал создать аккаунт, на <a.v.konovalov87@mail.ru> мне ничего не пришло.

Здравствуйте, если после заполнения регистрационной формы вы были перенесены на новую страницу с надписью типа "check your email box", это значит что письмо на указанный ящик точно было отправлено. 
На локале, трудно сказать, что у вас пошло не так, ибо у нас все работает. Возможно у вас неверно была заполнена регистрационная форма, и аккаунт просто не создался (если в директории svg-editor/media была создана папка с вашим логином, то это значит, что аккаунт точно был создан). 
Если вам не трудно, не могли бы вы создать аккаунт на нашем сайт, там я могу видеть логи и через админку могу посмотреть информацию об аккаунте.

**Comment by Mazdaywik** [comment]
Ну так я на сайте и создаю аккаунт.

![image](https://user-images.githubusercontent.com/1309859/198945322-0f49550b-8e75-40f5-9bca-0962aa215ede.png)

После нажатия на `Create Your Account!`:

![image](https://user-images.githubusercontent.com/1309859/198945393-e3cc7ef8-d615-44a0-ba0d-160c8c04f226.png)

**Comment by Kabane-UN** [comment]
> Ну так я на сайте и создаю аккаунт.
> 
> ![image](https://user-images.githubusercontent.com/1309859/198945322-0f49550b-8e75-40f5-9bca-0962aa215ede.png)
> 
> После нажатия на `Create Your Account!`:
> 
> ![image](https://user-images.githubusercontent.com/1309859/198945393-e3cc7ef8-d615-44a0-ba0d-160c8c04f226.png)
> 

This password is too common

**Comment by Mazdaywik** [comment]
Если пароль отвергается по каким-то причинам, значит, об этом нужно уведомлять пользователя.

**Comment by AngelicHedgehog** [comment]
> Если пароль отвергается по каким-то причинам, значит, об этом нужно уведомлять пользователя.

Согласен, наша оплошность, учтём.
